### ISSUE TITLE
Add Themes

### ISSUE THREAD

**Issue by LunaticHacker** [LunaticHacker/lemmy-terminal-viewer#2]
Allow user to configure <s>(non-exhaustive list)</s> :
- [ ] theme
<s>- [ ]  parameters in API calls (eg: limit when fetching posts)</s>
<s>- [ ] default instance</s>

**Comment by LunaticHacker** [comment]
updated with ca15b5a1ecfad815c4aea39c3cd6d73739655ff3

**Comment by aadilayub** [comment]
Hello! sorry to revive this dead issue. Could you point me to instructions for how to configure themes (if any exist)?

**Comment by LunaticHacker** [comment]
https://github.com/LunaticHacker/lemmy-terminal-viewer#setting-up-configs-optional

you can set your own primary,secondary and bg colors in the config

The theme colors can be an rgb string of the form "255, 255, 255" or a string that references the colors from your terminal theme: Reset, Black, Red, Green, etc

**Comment by aadilayub** [comment]
got it, thank you!
